# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - echo "Your build and test goes here..."
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
      - step:
          name: 'Security scan'
          script:
            - echo "Your security scan goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
  branches:
    main:
      - step:
          name: 'Build and Test'
          script:
            - echo "Your build and test goes here..."
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
      - step:
          name: 'Security scan'
          script:
            - echo "Your security scan goes here..."
      - step:
          name: 'Create Artifact'
          script:
            - git archive --format=tar.gz main -o table_planner_artifact.tar.gz
          artifacts:
            - table_planner_artifact.tar.gz
      - step:
          name: 'Deployment to Production'
          deployment: production
          caches:
            - node
          script:
            - echo "Your deployment to production script goes here..."
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_API_KEY: '60143d53-4116-4e21-a1c6-398aefa89225'
                HEROKU_APP_NAME: 'table-planner-user-bitbucket'
                URI: 'mongodb+srv://admin:admin123456@myfirstcluster.p2ff0.mongodb.net/TablePlanner?retryWrites=true&w=majority'
                secretOrKey: 'HungKhaAnKietTuan'
                nodeMailerEmail: 'peterpans2025@gmail.com'
                nodeMailerPassword: 'anhchien0123'
                nodeMailerClId: '968409339132-737scfdqpvfb4od8to8s83gbiegfn03u.apps.googleusercontent.com'
                nodeMailerSecret: 'Iponu5pDR1ds4rbhe-bl2dod'
                nodeMailerRefreshToken: '1//04Ww-5zvu-BE1CgYIARAAGAQSNwF-L9Ir2YOkn1AcO3Yx9LkZsXj7Og9LyS-AHc1PuPUob5Z5lBeeMu4E70Qj3jHx0vg31jTnU4M'
                nodeMailerAccessToken: 'ya29.a0AfH6SMDNZG_wXeFM4qH7fXexHcleMHtunrvHm6LGZnYe9evM9tgWSHkBmoLgfzpLf_zaNV41Zsn19epshxb2_53194rpDMDGaalOkvy-MKhzBL3ZRcVr4zw5HDxRcNt4ql48AgyA8dYIejfVq7a3focGtZvrwMwt0ujm_p9fK34'
                ZIP_FILE: 'table_planner_artifact.tar.gz'
                WAIT: 'true'