version: "3"

services:
  table-planing-admin:
    image: hcmus/table-planner-user-backend
    build:
      context: .
    container_name: table-planner-user-backend
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
